spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.13/mart?characterEncoding=utf-8&useSSL=false
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.13
    port: 6379
server:
  context-path: /sell

wechat:
  mpAppId: wx710aa2f8ef22a0ae
  mpAppSecret: 528a358eb43e0fe5f2c4296f0338fa3d
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://mart.natapp1.cc/sell/pay/notify
  templateId:
    orderStatus: 32J2K4BtG6cX3a_PYGQS68e8LwIPAGlFnGRX5ObwrQk  #Id for order status change

projectUrl:
  wechatMpAuthorize: http://mart.natapp1.cc
  wechatOpenAuthorize: http://mart.natapp1.cc
  sell: http://mart.natapp1.cc


